spring:
  rabbitmq:
    host: 192.168.227.130
    username: admin
    password: admin
    virtual-host: /admin
    port: 5672
  mail:
    protocol: smtp
    #发送方的邮箱smtp服务地址
    host: smtp.sina.cn
    username: verygoodwlk@sina.cn
    password: ken123456
server:
  port: 8086